# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'open-uri'

User.destroy_all
Restaurant.destroy_all

User.create!(username: 'demo_user', password: '123456')
User.create!(username: 'Fred Flinstone', password: '123456')
User.create!(username: 'Gordon Ramsey', password: '123456')

rest1 = Restaurant.create!(name: 'A Mano', owner_id: 1, description: 'a Mano means “by hand” in Italian and refers to the way in which the kitchen and the bar approach the creation of each and every dish and cocktail. Each morning, our cooks make our pasta fresh by hand. It is with this same level of care and attention to detail that every dish on the menu is executed. We use our strong relationships with farmers and purveyors to create a delicious selection of antipasti, fresh salads, pizzas and pastas that evolve and change with the seasons. Italian at heart and influenced by the bounty of Northern California, a meal at a Mano can be enjoyed any day of the week.', cuisine: 'Italian', price: '$$')
rest2 = Restaurant.create!(name: 'Benihana', owner_id: 2, description: 'Welcome to Benihana, where you’ll find a dining experience unlike any other! Highly skilled and well-trained, your personal chef will entertain you while cooking such favorites as steak, chicken, seafood and fresh vegetables in traditional Japanese style on a hibachi table. Reservations are recommended at select locations.', cuisine: 'Japanese-American', price: '$$$')
rest3 = Restaurant.create!(name: 'Brera Osteria', owner_id: 3, description: 'BRERA osteria marks a new chapter in Italian cuisine on the Las Vegas Strip. Savor homemade pastas, wood oven-baked breads, cured meats, olive oils, and mouthwatering mozzarella. One of the best places to eat in Las Vegas for lunch or dinner— BRERA is all about enjoying the moment. Find this gem in the heart of St. Mark’s Square in the Grand Canal Shoppes.', cuisine: 'Italian', price: '$$$')
rest4 = Restaurant.create!(name: 'Carbone', owner_id: 1, description: 'Carbone is an Italian-American restaurant created by Mario Carbone, Rich Torrisi and Jeff Zalaznick. The restaurant pays homage to the essence of the great Italian-American restaurants of mid-20th century in New York, where delicious, exceptionally well-prepared food was served in settings that were simultaneously elegant, comfortable and unpretentious. The food nods to that same history, but takes its culinary cues from the great talents and techniques of the present and of the future. Familiar dishes like Seafood Salad, Linguini Vongole, Lobster Fra Diavola, Chicken Scarpariello and Veal Parmesan elevated to a new level.', cuisine: 'Italian', price: '$$$')
rest5 = Restaurant.create!(name: 'Chica', owner_id: 2, description: 'CHICA a Celebration of Latin Flavors by Celebrity Chef Lorena Garcia, opened its doors in May of 2017. CHICA delivers the robust and vibrant flavors of Latin American cuisine combined with a dynamic wine and mixology program to The Venetian Las Vegas and Miami’s MiMo district. CHICA’s menu was crafted by Celebrity Chef Lorena Garcia and draws inspiration from classic renditions of Latin dishes, giving guests the opportunity to explore the flavors of Latin American cuisine as one culture. CHICA’s menu features influences from Venezuela, Peru, Brazil, Mexico and Argentina, among many others. CHICA is open daily for breakfast, lunch, dinner and weekend brunch.', cuisine: 'Mexican', price: '$$$')
rest6 = Restaurant.create!(name: 'Cipriani', owner_id: 3, description: 'Classic glamour. Since it opened as Harry’s Bar in Venice, Italy, Cipriani has expanded to New York, Hong Kong, Monte Carlo and Ibiza, and now to its first restaurant on the West Coast. Cipriani exudes timeless elegance with nautical touches, glossy walnut and chrome accents, and terrazzo floors. Look for signature classics such as the original carpaccio alla Cipriani, vanilla meringue and the iconic Bellini, invented by Giuseppe Cipriani Sr. in 1948.', cuisine: 'Italian', price: '$$$')
rest7 = Restaurant.create!(name: 'Coyo', owner_id: 1, description: 'Miami’s freshest Mexican street food experience. At Coyo Taco, guacamole is smashed to order and tortillas are handcrafted on-site in an authentic Mexican tradition. Vegetables are farm fresh and locally sourced. meat and seafood are naturally raised and humanely treated. Aguas frescas and margaritas are made from scratch. staying true to our todo fresco, or ‘everything fresh’ philosophy, our ingredients are 100% natural.', cuisine: 'Mexican', price: '$$$')
rest8 = Restaurant.create!(name: 'Delilah', owner_id: 2, description: 'Wynn Las Vegas and acclaimed global hospitality partner h.wood Group present a modern-day supper club, Delilah at Wynn Las Vegas. Located in the exclusive Tower Suites enclave, Delilah at Wynn Las Vegas offers a true supper club atmosphere, inspired by the earliest showrooms of Las Vegas in the 1950s. The venue has multiple environments for guests to dine and socialize, with live music and special performances, DJs and Sunday Night Jazz.', cuisine: 'American', price: '$$$')
rest9 = Restaurant.create!(name: 'Dumpling Time', owner_id: 3, description: 'A Dumpling-And-Beer house from the acclaimed restaurant team behind San Francisco\'s Michelin-starred Omasake and Niku Steakhouse. This modern Cal-Asian eatery—where visitors can watch dumplings being made fresh right before their eyes—is casual, social and fun. The menu focuses on freshly-made dumplings in the Asian tradition. Think locally sourced ingredients, unique fillings, and shareable plates.', cuisine: 'Cal-Asian', price: '$$$')
rest10 = Restaurant.create!(name: 'Hell\'s Kitchen', owner_id: 1, description: 'Located in front of Caesars Palace, the restaurant boasts floor-to-ceiling windows overlooking the famous Las Vegas Strip, red and blue design details in the show kitchen, a private dining room and a contemporary bar serving the latest trends in mixology. The Red and Blue kitchens serve up modern lunch and dinner menus including Hell’s Kitchen signature dishes made with the highest quality ingredients.', cuisine: 'American', price: '$$$')
rest11 = Restaurant.create!(name: 'Mamahuhu', owner_id: 2, description: 'We envision a future in which delicious, affordable, sustainably-sourced food is the norm and Chinese-American cuisine plays a central role. A future where happy and healthy dinners are enjoying delicious, responsibly sourced Chinese-American food as part of their weekly dining routines.', cuisine: 'Chinese-American', price: '$$$')
rest12 = Restaurant.create!(name: 'Mojitos', owner_id: 3, description: 'The name, Mojitos, only starts to tell this unique restaurant’s story. A Mojito is the traditional Cuban highball cocktail. The classic recipe calls for five ingredients: rum, sugar, lime juice, soda and mint leaves.

Of course, Mojitos takes its classic, namesake drink to the next level. While the traditional mojito remains a favorite, Mojitos mixologists have developed a range of cocktails that showcase the traditional drink with a dash of contemporary creativity. Whether it’s a traditional Mojito, Mojito Razz, Mojito Cosmo or any other of the other specialty Mojitos, we know you’ll love them.

The restaurant has a similar recipe for success. Like the traditional and specialty Mojito drinks, the restaurant prides itself in serving traditional Cuban cuisine with generous portions, an artisan chef’s touch and a dash of modern culinary style – a fusion that must be experienced.

In addition to the exceptional food and drinks, Mojitos also has a tradition that no other Cuban restaurant can claim –  the festive, fun, lively ambiance that includes live Cuban music and dancing four nights a week.', cuisine: 'Cuban', price: '$$$')
rest13 = Restaurant.create!(name: 'Mon Ami Gabi', owner_id: 1, description: 'Take in the aroma of authentic French cuisine: our signature Onion Soup Au Gratin, Steak Frites and Chicken Grand-Mére. Enjoy thoughtfully selected wine from our historic rolling wine cart. Indulge in a savory bite of Chocolate Mousse or Profiteroles.

Located in the heart of Sin City at the Paris Hotel and Casino.', cuisine: 'French', price: '$$$')
rest14 = Restaurant.create!(name: 'Morimoto', owner_id: 2, description: 'The contemporary Japanese design of Morimoto Las Vegas combines delicate Japanese beauty and elegance, with exotic photographs by Yasumichi Morita, to create a stunning restaurant with a signature Morimoto touch. From the moment guests arrive, they will begin to experience Las Vegas in a new way; The Morimoto way.', cuisine: 'Japanese', price: '$$$')
rest15 = Restaurant.create!(name: 'Moya', owner_id: 3, description: 'Fun Ethiopian spot located in the heart of San Francisco.', cuisine: 'Ethiopian', price: '$$$')
rest16 = Restaurant.create!(name: 'North India', owner_id: 1, description: 'Made direct from India, our traditional Tandoors, or clay ovens, cook meats, breads and more the traditional way; with high heat from charcoal for that smoked aroma that\'s to die for! Sink your teeth into our succulent Chicken Tikka, delicately marinated and lovingly cooked to juicy perfection. Accompany that with fluffy Naan bread and an ice-cold pint of Kingfisher for the perfectly rounded gastronomical experience!', cuisine: 'Indian', price: '$$$')
rest17 = Restaurant.create!(name: 'Rice', owner_id: 2, description: 'Chef Ali Shabani spent years methodically researching and developing the Rice Kitchen menu in his South Miami test kitchen, mining the family’s precious catalogue of Mediterranean recipes passed down through generations, and then modernizing those dishes in collaboration with patrons at his existing restaurants, family and culinary experts.', cuisine: 'Mediterranean', price: '$$$')
rest18 = Restaurant.create!(name: 'Sergio\'s', owner_id: 3, description: 'Sergios is known for the unique combination of our family’s authentic recipes with typical Cuban and American dishes.  Its the fusion of these two worlds that define not only the food we serve bu the culture of “mi gente” that makes up the Sergio’s familia…Cuban roots mixed with new American culture. We know both the Spanish and the English language and we speak them interchangeably because sometimes there is nothing better than a particular Spanish word to finish a thought or describe something. Our unique personality represents the way we talk, the way we live and the way we cook. Bienvenidos a Sergios.', cuisine: 'Cuban', price: '$$$')
rest19 = Restaurant.create!(name: 'Spago', owner_id: 1, description: 'Wolfgang Puck’s legendary flagship fine dining restaurant Spago is recognized for igniting Las Vegas’s dining scene into a culinary epicenter. Puck’s revolutionary Las Vegas Strip restaurant debuts with an entirely new look and menu and the exceptional level of service for which the restaurant is best known. The restaurant is beautifully situated for al fresco dining in front of the Bellagio Fountains. Spago’s re-imagined menu features Puck’s signature California fare paired with modern technique and inspiration from his chef’s weekly trips to the Santa Monica Farmer’s Market. At lunch and dinner, the market-driven menus feature handmade pastas, wood-oven pizzas, fresh seafood, all-natural meats and prime steaks, alongside handcrafted cocktails and a robust wine list. To complete the meal, dessert complements the menu with an array of seasonal delights sure to make your experience the Best Las Vegas Restaurant. Design and collaboration by Gelila Puck and Italian architects Massimiliano Locatelli and Annamaria Scevola of CLS Architetti, and inspired by Spago’s original flagship location in Beverly Hills, the new venue has a sleek look and warm feel. In the main dining room, beautiful floor-to-ceiling floating glass windows surround the space, imparting picturesque views of Bellagio’s famed lake. Two exquisite chandeliers highlight the room’s modern art pieces, while bold accents featuring rich hues of black iron, velvet walnut and polished grey express a contemporary aesthetic. The next era of Vegas dining begins here.', cuisine: 'Italian', price: '$$$')
rest20 = Restaurant.create!(name: 'Volcano Curry', owner_id: 1, description: 'Japanese-style curry with a list of topping options, along with noodles & sandwiches.', cuisine: 'Japanese', price: '$$$')


rest1.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/a-mano-sf/AMano_PChang_4330.0.jpg'), filename: 'a-mano.jpg')
rest2.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/benihana-mia/Benihana_1%2BT.jpg'), filename: 'benihana.jpg')
rest3.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/brera-lv/interior-3_1920x1080.jpg.resize.0.0.1200.630.jpg'), filename: 'brera.jpg')
rest4.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/carbone-lv/Carbone_Red_Room_Aria.0.0.1446003814.jpg'), filename: 'carbone.jpg')
rest5.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/chica-lv/interior-1_1920x1080.jpg'), filename: 'chica.jpg')
rest6.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/cipriani-lv/Cipriani_1__FIRST_PHOTO_.0.jpg'), filename: 'cipriani.jpg')
rest7.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/coyo-mia/1584051569.74.webp'), filename: 'coyo.webp')
rest8.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/delilah-lv/1_Wynn_Delilah_Ceiling%2520Sweep_Robert%2520Miller6-1920x602.jpg'), filename: 'delilah.jpg')
rest9.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/dumpling-time-sf/DumplingTime_PChang-2988.jpg'), filename: 'dumpling-time.jpg')
rest10.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/hells-kitchen-lv/Hell_s_Kitchen___MAIN_PHOTO.jpg'), filename: 'hells-kitchen.jpg')
rest11.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/mamahuhu-sf/Mamahuhu_PChang_2022.jpg'), filename: 'mamahuhu.jpg')
rest12.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/mojitos-mia/Screen+Shot+2021-09-29+at+11.31.51+AM.png'), filename: 'mojitos.jpg')
rest13.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/mon-ami-gabi-lv/Vegas_Le_Cabaret_Private_Parties.jpg'), filename: 'mon-ami-gabi.jpg')
rest14.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/morimoto-lv/MORIMOTO_SushiBar1-1.jpg'), filename: 'morimoto.jpg')
rest15.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/moya-sf/hcmp99824_355853.jpeg'), filename: 'moya.jpeg')
rest16.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/north-india-sf/unnamed-4.jpg'), filename: 'north-india.jpg')
rest17.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/rice-mia/4cf6a5fe6356089034f44d1e095b02db_-united-states-florida-miami-dade-county-miami-rice-mediterranean-kitchen-305-705-6090htm.png'), filename: 'rice.png')
rest18.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/sergios-mia/MIA_105Sergios00NEWPPP.jpg'), filename: 'sergios.jpg')
rest19.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/spago-lv/1566510877.84.webp'), filename: 'spago.webp')
rest20.photo.attach(io: open('https://open-table-seeds.s3.us-west-1.amazonaws.com/OT-imgs/volcano-curry-sf/seating-area-in-the-restaurant.jpg'), filename: 'volcano-curry.jpg')
